import Foundation

struct DefaultPositiveNoteProvider: PositiveNoteProviding {
    
    public let notes: [String] = [
        "Notice your breath",
        "Slow inhale",
        "Long exhale",
        "Gentle breath",
        "Breathe slowly",
        "Count three breaths",
        "Even breaths",
        "Follow the breath",
        "Anchor the breath",
        "Lengthen exhale",
        "Soften your exhale",
        "Just one breath",
        "Return to breath",
        "Back to breath",
        "Stay with breath",
        "Breathe and release",
        "Steady breathing",
        "Calm breathing",
        "Breathing gently",
        "Breathing slowly",
        "Relax into breath",
        "Soft breathing",
        "Quiet breathing",
        "Breathing easy",
        "Breathe calmly",
        "Breathe steadily",
        "Trust your breath",
        "Gentle exhale",
        "Ease exhale",
        "Smooth breath",
        "Soft inhale",
        "Slow your breath",
        "One gentle breath",
        "One slow breath",
        "Breath by breath",
        "Breath is home",
        "Inhale calm",
        "Exhale ease",
        "Inhale peace",
        "Exhale stress",
        "Relax your jaw",
        "Soften your gaze",
        "Drop the shoulders",
        "Relax shoulders",
        "Ease your shoulders",
        "Unclench your fists",
        "Relax your hands",
        "Soften your face",
        "Unfurrow your brow",
        "Relax your eyes",
        "Rest your eyes",
        "Relax your tongue",
        "Ease your neck",
        "Relax your back",
        "Open your chest",
        "Sit tall",
        "Rest shoulders",
        "Rest hands",
        "Rest gently",
        "Relax posture",
        "Ease your spine",
        "Soften your spine",
        "Relax your hips",
        "Relax your pelvis",
        "Relax your legs",
        "Relax your feet",
        "Ground your feet",
        "Soften your feet",
        "Relax your toes",
        "Soften your toes",
        "Ease your arms",
        "Relax your arms",
        "Relax fingers",
        "Ease your fingers",
        "Relax lips",
        "Soften your lips",
        "Unclench your teeth",
        "Relax your teeth",
        "Ease your brow",
        "Relax your scalp",
        "Ease your scalp",
        "Loosen the neck",
        "Drop your jaw",
        "Rest your back",
        "Ease the back",
        "Release tension",
        "Release shoulders",
        "Release your jaw",
        "Release your neck",
        "Release your chest",
        "Release your hands",
        "Release your belly",
        "Release your tongue",
        "Hear one sound",
        "Notice silence",
        "Notice sounds",
        "Notice stillness",
        "Listen softly",
        "Listen closely",
        "See one colour",
        "Notice the light",
        "Notice colours",
        "Notice warmth",
        "Notice coolness",
        "Feel the ground",
        "Feel your feet",
        "Feel your seat",
        "Feel your back",
        "Feel your hands",
        "Feel your breath",
        "Feel your chest",
        "Feel your heartbeat",
        "Notice heartbeat",
        "Notice pulse",
        "Notice body",
        "Notice posture",
        "Feel support",
        "Notice support",
        "Feel clothing",
        "Feel fabric",
        "Feel skin",
        "Feel air",
        "Feel breeze",
        "Notice temperature",
        "Notice contact",
        "Notice touch",
        "Notice one sound",
        "Notice one thing",
        "Notice this moment",
        "Choose kindness",
        "Kind inner voice",
        "Offer yourself kindness",
        "Treat yourself gently",
        "You are safe",
        "You are enough",
        "Let yourself rest",
        "Thank your body",
        "Thank your breath",
        "Grateful for now",
        "Be grateful",
        "Grateful for breath",
        "Hold yourself kindly",
        "Hold yourself gently",
        "Soften inner voice",
        "Feel kindness",
        "Choose compassion",
        "Practice compassion",
        "Be kind",
        "Speak kindly",
        "Act gently",
        "Show kindness",
        "Kind reminder",
        "Be patient",
        "Kind attention",
        "Pay attention",
        "Calm attention",
        "Offer care",
        "Offer compassion",
        "Value kindness",
        "Small kindness",
        "Practice kindness",
        "Allow kindness",
        "Roots down",
        "Ground solid",
        "Mountain steady",
        "Gentle river",
        "Clouds passing",
        "Sky wide",
        "Warm sunlight",
        "Soft breeze",
        "Steady shore",
        "Calm harbor",
        "Calm waves",
        "Peaceful sky",
        "Calm horizon",
        "Quiet sky",
        "Open sky",
        "Clear sky",
        "Bright sky",
        "Gentle rain",
        "Soft rain",
        "Morning light",
        "Calm evening",
        "Fresh dew",
        "Quiet forest",
        "Calm lake",
        "Still lake",
        "Gentle stream",
        "Quiet river",
        "Calm ocean",
        "Gentle waves",
        "Soft wind",
        "Gentle breeze",
        "Calm meadow",
        "Quiet meadow",
        "Peaceful garden",
        "Calm blossoms",
        "Leaf falling",
        "Falling leaves",
        "Spring light",
        "Calm autumn",
        "Be here now",
        "This moment only",
        "Right now",
        "Only now",
        "Now is enough",
        "Nowhere to go",
        "Nothing to fix",
        "Nothing to do",
        "Simply be here",
        "Stay present",
        "Stay here",
        "Stay open",
        "Stay kind",
        "Just this",
        "Just now",
        "Just one thing",
        "One thing only",
        "One step",
        "One moment",
        "Tiny pause",
        "Pause here",
        "Pause gently",
        "Pause softly",
        "Take a pause",
        "Allow now",
        "Allow this",
        "Allow ease",
        "Let go",
        "Let be",
        "Trust this moment",
        "Trust now",
        "Trust here",
        "Peace now",
        "Find calm",
        "Find quiet",
        "Soften now",
        "Be steady",
        "Be gentle",
        "Go easy",
        "Begin again",
        "Fresh start",
        "New moment",
        "Start again",
        "Right here",
        "Here only",
        "This is now",
        "This breath",
        "This step",
        "This pause",
        "Calm inhale",
        "Calm exhale",
        "One soft exhale",
        "Relax shoulders down",
        "Relax your spine",
        "Ease your hips",
        "See one shape",
        "Feel both feet",
        "Be gentle now",
        "Offer yourself care",
        "Gentle sunset",
        "Only this breath",
        "Slow steady breath",
        "One calm breath",
        "Each soft breath",
        "Breathe with ease",
        "Smooth exhale",
        "Easy inhale",
        "Gentle inhale",
        "Quiet exhale",
        "Softly breathing",
        "Deep slow breath",
        "Breath is steady",
        "Rest with breath",
        "Settle the breath",
        "Breathing in calm",
        "Breathing out ease",
        "Release the jaw",
        "Relax the brow",
        "Ease the shoulders",
        "Rest the shoulders",
        "Relax the hands",
        "Ease the hands",
        "Relax the arms",
        "Ease the arms",
        "Rest the hands",
        "Relax the legs",
        "Ease the legs",
        "Relax the feet",
        "Ease the feet",
        "Rest the feet",
        "Relax the toes",
        "Ease the toes",
        "Relax the back",
        "Rest the back",
        "Relax the chest",
        "Ease the chest",
        "Relax the hips",
        "Ease the hips",
        "Relax the pelvis",
        "Ease the pelvis",
        "Relax the spine",
        "Ease the spine",
        "Soften the spine",
        "Soften the neck",
        "Soften the brow",
        "Soften the eyes",
        "Soften the jaw",
        "Soften the lips",
        "Soften the face",
        "Soften the hands",
        "Soften the feet",
        "Soften the shoulders",
        "Soften the posture",
        "Hear the silence",
        "Hear the breeze",
        "Hear the stillness",
        "Hear the calm",
        "Notice your seat",
        "Notice your support",
        "Notice the chair",
        "Notice the floor",
        "Notice your weight",
        "Notice your skin",
        "Notice the air",
        "Notice the breeze",
        "Notice your clothes",
        "Notice the fabric",
        "Notice your heartbeat",
        "Feel your pulse",
        "Feel your belly",
        "Feel your posture",
        "Feel the calm",
        "Offer yourself peace",
        "Offer yourself rest",
        "Offer yourself ease",
        "Offer yourself love",
        "Offer yourself patience",
        "You are calm",
        "You are whole",
        "You are loved",
        "You are steady",
        "You are grounded",
        "Thank your mind",
        "Thank your heart",
        "Grateful for body",
        "Grateful for life",
        "Kindness right now",
        "Choose soft words",
        "Choose gentle words",
        "Choose patience",
        "Choose kindness now",
        "Calm forest",
        "Peaceful forest",
        "Still forest",
        "Quiet tree",
        "Steady tree",
        "Relax fully",
        "Stay calm",
        "Feel calm",
        "Stay steady",
        "Steady breath",
        "Rest softly",
        "Relax gently",
        "Calm and steady"
    ]
    
    func randomNote() -> String { notes.randomElement() ?? "Begin again" }
}
