import Foundation

struct DefaultPositiveNoteProvider: PositiveNoteProviding {
    private let notes = [
        "Notice your breath",
        "Relax the jaw",
        "Unclench your fists",
        "Drop the shoulders",
        "Soften the face",
        "Breathe in slowly",
        "Long exhale now",
        "Feel your feet",
        "Be here now",
        "One thing at once",
        "Listen, don't fix",
        "Label: thinking",
        "Return to breath",
        "Count three breaths",
        "Slow down",
        "Sip the moment",
        "Posture tall",
        "Kind to yourself",
        "Thank your body",
        "This is enough",
        "Let thoughts pass",
        "Ride the wave",
        "Name five things",
        "Feel the air",
        "Smile gently",
        "Loosen the brow",
        "Ease the neck",
        "Open the chest",
        "Drop the story",
        "Notice contact points",
        "Ground through soles",
        "Head to toe scan",
        "Relax the tongue",
        "Soft belly breath",
        "Hands unclenched",
        "Eyes soft",
        "Neck long",
        "Jaw unhooked",
        "Shoulders easy",
        "Breath over noise",
        "Anchor in breath",
        "Let be",
        "Tiny kindness now",
        "You are safe",
        "Pause, then proceed",
        "Observe, not judge",
        "Curious, not certain",
        "Hear the sounds",
        "Feel the ground",
        "Notice temperature",
        "Name this feeling",
        "Allow and accept",
        "Tension out",
        "Breath like waves",
        "Inhale calm",
        "Exhale ease",
        "Calm within",
        "Soften and settle",
        "Just this breath",
        "Let shoulders drop",
        "Back straight",
        "Face relaxed",
        "Hands relaxed",
        "Unplug a moment",
        "Rest your eyes",
        "Kind inner voice",
        "Grateful for now",
        "I am present",
        "Whole body breath",
        "Aware of space",
        "Gentle attention",
        "Ease into now",
        "Mind like sky",
        "Thoughts are clouds",
        "Breathing is home",
        "Savour this sip",
        "Notice one colour",
        "Name one scent",
        "Feel clothing",
        "Hear one note",
        "Count to five",
        "Micro-break time",
        "Loosen your grip",
        "Accept, then act",
        "Patience practice",
        "Compassion first",
        "Kindness counts",
        "Calm body, mind",
        "Breathe, then act",
        "Present, not perfect",
        "Let go gently",
        "Steady and soft",
        "Quiet within",
        "Peace on purpose",
        "Trust this moment",
        "Breath leads",
        "Return to now",
        "Here, completely",
        "Simple, not easy",
        "Begin again"
    ]
    func randomNote() -> String { notes.randomElement() ?? "Begin again" }
}
